// <auto-generated />
using System;
using DbRepositoryAdapter;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbRepositoryAdapter.Migrations
{
    [DbContext(typeof(DbRepositoryAdapterContext))]
    partial class DbRepositoryAdapterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbRepositoryAdapter.Entidades.NegociacoesDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MaiorPreco")
                        .HasPrecision(14, 8)
                        .HasColumnType("decimal(14,8)");

                    b.Property<decimal>("MaiorPrecoOfertado")
                        .HasPrecision(14, 8)
                        .HasColumnType("decimal(14,8)");

                    b.Property<decimal>("MenorPreco")
                        .HasPrecision(14, 8)
                        .HasColumnType("decimal(14,8)");

                    b.Property<decimal>("MenorPrecoOfertado")
                        .HasPrecision(14, 8)
                        .HasColumnType("decimal(14,8)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(14, 8)
                        .HasColumnType("decimal(14,8)");

                    b.Property<decimal>("QuantidadeNegociada")
                        .HasPrecision(14, 8)
                        .HasColumnType("decimal(14,8)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Sigla")
                        .IsUnique();

                    b.ToTable("NegociacoesDoDia");
                });

            modelBuilder.Entity("DbRepositoryAdapter.Entidades.NegociacoesHistoricoDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MaiorPreco")
                        .HasPrecision(14, 8)
                        .HasColumnType("decimal(14,8)");

                    b.Property<decimal>("MaiorPrecoOfertado")
                        .HasPrecision(14, 8)
                        .HasColumnType("decimal(14,8)");

                    b.Property<decimal>("MenorPreco")
                        .HasPrecision(14, 8)
                        .HasColumnType("decimal(14,8)");

                    b.Property<decimal>("MenorPrecoOfertado")
                        .HasPrecision(14, 8)
                        .HasColumnType("decimal(14,8)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(14, 8)
                        .HasColumnType("decimal(14,8)");

                    b.Property<decimal>("QuantidadeNegociada")
                        .HasPrecision(14, 8)
                        .HasColumnType("decimal(14,8)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Sigla");

                    b.ToTable("HistoricoNegociacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
